# Generated by Django 6.0.6 on 2026-06-30 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Falta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data da Falta')),
                ('quantidade_tempos', models.IntegerField(default=1, verbose_name='Quantidade de Tempos Omitidos')),
                ('status', models.CharField(choices=[('INJUSTIFICADA', 'Injustificada'), ('PENDENTE', 'Pendente de Validação'), ('JUSTIFICADA', 'Justificada')], default='INJUSTIFICADA', max_length=20, verbose_name='Estado da Falta')),
                ('data_registo', models.DateTimeField(auto_now_add=True, verbose_name='Data de Registo no Sistema')),
                ('cadeira_turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faltas_registadas', to='academico.cadeiraturma', verbose_name='Disciplina/Turma')),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faltas', to='academico.perfilestudante', verbose_name='Estudante')),
            ],
            options={
                'verbose_name': 'Falta',
                'verbose_name_plural': 'Faltas',
                'ordering': ['-data', '-data_registo'],
            },
        ),
        migrations.CreateModel(
            name='Justificativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField(verbose_name='Motivo do Absentismo')),
                ('documento_anexo', models.FileField(upload_to='justificativos/%Y/%m/', verbose_name='Comprovativo (PDF/Imagem)')),
                ('data_submissao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Submissão')),
                ('feedback_professor', models.TextField(blank=True, null=True, verbose_name='Parecer do Professor')),
                ('data_avaliacao', models.DateTimeField(blank=True, null=True, verbose_name='Data da Avaliação')),
                ('falta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='justificativa_associada', to='ausencias.falta', verbose_name='Falta Correspondente')),
            ],
            options={
                'verbose_name': 'Justificativo',
                'verbose_name_plural': 'Justificativos',
            },
        ),
    ]
