# Generated by Django 6.0.6 on 2026-06-30 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Disciplina')),
                ('sigla', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Sigla')),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome da Turma')),
                ('turno', models.CharField(choices=[('MANHA', 'Manhã'), ('TARDE', 'Tarde'), ('NOITE', 'Noite')], default='NOITE', max_length=10, verbose_name='Turno')),
                ('ano_letivo', models.IntegerField(default=2026, verbose_name='Ano Letivo')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
            },
        ),
        migrations.CreateModel(
            name='PerfilEstudante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_estudante', models.CharField(max_length=20, unique=True, verbose_name='Número de Matrícula')),
                ('utilizador', models.OneToOneField(limit_choices_to={'role': 'ESTUDANTE'}, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_estudante', to=settings.AUTH_USER_MODEL, verbose_name='Utilizador')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estudantes', to='academico.turma', verbose_name='Turma')),
            ],
            options={
                'verbose_name': 'Perfil de Estudante',
                'verbose_name_plural': 'Perfis de Estudantes',
            },
        ),
        migrations.CreateModel(
            name='CadeiraTurma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professor', models.ForeignKey(blank=True, limit_choices_to={'role': 'PROFESSOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cadeiras_lecionadas', to=settings.AUTH_USER_MODEL, verbose_name='Professor Responsável')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas_vinculadas', to='academico.disciplina', verbose_name='Disciplina')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cadeiras', to='academico.turma', verbose_name='Turma')),
            ],
            options={
                'verbose_name': 'Disciplina da Turma',
                'verbose_name_plural': 'Disciplinas das Turmas',
                'unique_together': {('turma', 'disciplina')},
            },
        ),
    ]
